const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.biz", "sharklasers.com", "grr.la", "temp-mail.org", "temp-mail.io",
  "temp-mail.info", "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "maildrop.cc", "getnada.com", "nada.email", "throwaway.email", "yopmail.com",
  "yopmail.fr", "yopmail.net", "yopmail.org", "mail-temp.com", "mailtempm.com",
  "tempmail.space", "tempmail.net", "tempmail.org", "dispostable.com", "mintemail.com",
  "spambox.us", "spambox.info", "spamgourmet.com", "spamfree24.org", "spamfree24.net",
  "spamfree24.com", "spamfree24.eu", "spamfree24.info", "spamfree24.de",
  "mailexpire.com", "thankyou2010.com", "trashmail.com", "trashmail.net",
  "trashmail.org", "trashmail.me", "wegwerfmail.de", "wegwerfmail.net",
  "wegwerfmail.org", "mytrashmail.com", "mailmetrash.com", "dontreg.com",
  "no-more-files.com", "nothingtoseehere.com", "sofort-mail.de",
  "tempinbox.com", "throwaway.de", "throwaway.email", "thrownm.com",
  "tittbit.in", "toiea.com", "topranklist.de", "trashymail.com",
  "tyldd.com", "uggsrock.com", "umail.net", "upliftnow.com",
  "vipmail.name", "vipmail.pw", "vipmail.eu", "vipmail.info",
  "walala.org", "webemail.me", "wegwerfmail.de", "wh4f.org",
  "whyspam.me", "writeme.com", "wronghead.com", "xagloo.com",
  "xemaps.com", "xents.com", "xmaily.com", "xoxy.net", "yep.it",
  "z1p.biz", "zehnminutenmail.de", "zippymail.info", "zoaxe.com",
  "zoemail.org", "mailmetrash.com", "mailnator.com", "mailnesia.com",
  "maily10.com", "mailmetrash.com", "mailmoat.com", "mailorc.com",
  "mailpick.biz", "mailpooch.com", "mailsac.com", "mailtemp.net",
  "mailtrix.net", "mailvia.com", "mailzi.ru", "malahov.de",
  "meinspamschutz.de", "meltmail.com", "messagebeamer.de",
  "minutere-mail.com", "moburl.com", "moncourrier.fr.nf",
  "monemail.fr.nf", "monmail.fr.nf", "msa.minsmail.com",
  "mt2009.com", "mx0.wwwnew.eu", "my10minutemail.com",
  "my-spam.org", "mytrashmail.com", "neomailbox.com",
  "nepwk.com", "nervmich.net", "netmails.com", "netmails.net",
  "neverbox.com", "nice-4u.com", "nincsmail.com", "nispuk.com",
  "no-mail.com", "nobulk.com", "noclickemail.com", "nogmailspam.info",
  "nomail.xl.cx", "nomail2me.com", "nomorespam.com", "nospam.ze.tc",
  "nospam4.us", "nospamfor.us", "nospamthanks.info",
  "nowmymail.com", "nowmymail.net", "ntlhelp.net", "nullbox.info",
  "obobbo.com", "odnorazovoe.ru", "onewaymail.com", "oozeemail.com",
  "ordinaryamerican.net", "otherinbox.com", "ourklips.com",
  "outlawspam.com", "ovpn.to", "owlpic.com", "pancakemail.com",
  "pavilionx2.com", "piki.ir", "pimpedupmyspace.com", "pjjkp.com",
  "plexolan.de", "poczta.onmicrosoft.com", "polizia-municipale.roma.it",
  "poofy.org", "pookmail.com", "privacy.net", "privatemail.com",
  "pro-tag.org", "promotionalt.com", "proxymail.eu", "prtnx.com",
  "punkass.com", "put2.net", "putthisinyourspamdatabase.com",
  "quickinbox.com", "rcpt.at", "re-gister.com", "reallymymail.com",
  "receiveee.com", "recyclemail.dk", "regbypass.com", "regspaces.blogspot.com",
  "rejectmail.com", "reliable-mail.com", "remail.cf", "rhyta.com",
  "rocketmail.com", "rollin.flubber.de", "rotzmail.de", "ruggedinbox.com",
  "rxcay.com", "safetymail.info", "safetypost.de", "sandelf.de",
  "saynotospams.com", "scdhn.com", "schafmail.de", "schrott-email.de",
  "secretemail.de", "secure-mail.biz", "selfdestructingmail.com",
  "selfdestructingmail.org", "sendfree.org", "sendingspecialflyers.com",
  "service4money.de", "sfil.net", "sharklasers.com", "shieldedmail.com",
  "shiftmail.com", "shitaway.usa.cc", "shitmail.de", "shitmail.me",
  "shitmail.org", "shitware.nl", "shmeriously.com", "shortmail.net",
  "sibmail.com", "sinnlos-mail.de", "siteposter.com", "skeefmail.com",
  "slapsfromlastnight.com", "slipry.net", "slopsbox.com", "slushmail.com",
  "smtp33.com", "snakerex.com", "sneakemail.com", "sneakmail.de",
  "snkmail.com", "socialfurry.org", "sofimail.com", "sofort-mail.de",
  "softpls.asia", "sogetthis.com", "spam.la", "spam.su", "spam4.me",
  "spamail.de", "spamarrest.com", "spambe-gone.com", "spambob.com",
  "spambob.org", "spambog.com", "spambog.de", "spambog.net",
  "spambox.us", "spamcannon.com", "spamcannon.net", "spamcero.com",
  "spamcon.org", "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
  "spamcowboy.org", "spamday.com", "spamdecoy.net", "spamex.com",
  "spamfree24.com", "spamfree24.de", "spamfree24.eu", "spamfree24.info",
  "spamfree24.net", "spamfree24.org", "spamgoes.in", "spamgourmet.com",
  "spamgourmet.net", "spamgourmet.org", "spamherelots.com", "spamhereplease.com",
  "spamhole.com", "spamify.com", "spaminator.de", "spamkill.info",
  "spaml.com", "spamlot.net", "spammotel.com", "spamobox.com",
  "spamoff.de", "spamsalad.in", "spamseymore.com", "spamslicer.com",
  "spamspameverywhere.com", "spamspot.com", "spamstack.net", "spamthis.co.uk",
  "spamthisplease.com", "spamtrail.com", "spamtroll.net", "spamwc.de",
  "speed.1s.fr", "spikio.com", "spoofmail.de", "spybox.de", "squizzy.de",
  "ssoia.com", "stanfordujjain.com", "starlight-breaker.net", "startbest.net",
  "starpower.space", "start-key.de", "statdvr.com", "stexsy.com",
  "stinkefinger.net", "stop-my-spam.com", "stuff.munrohk.com", "suremail.info",
  "svxr.org", "t.psh.me", "tafmail.com", "tagyourself.com", "talkinator.com",
  "tapchicuoihoi.com", "techemail.com", "techgroup.me", "teleworm.com",
  "teleworm.us", "temp-mail.com", "temp-mail.de", "temp-mail.org",
  "tempail.com", "tempe-mail.com", "tempemail.biz", "tempemail.co.za",
  "tempemail.com", "tempemail.net", "tempemail.org", "tempinbox.co.uk",
  "tempinbox.com", "tempmail.de", "tempmail.eu", "tempmail.it",
  "tempmail.net", "tempmail.org", "tempmail.us", "tempomail.fr",
  "temporarily.de", "temporaryemail.net", "temporaryforwarding.com",
  "temporarymail.org", "thankyou2010.com", "thecloudindex.com",
  "thej5.com", "thembones.com.au", "thespawningpool.com",
  "thisisnotmyrealemail.com", "thismail.net", "thraml.com",
  "threextm.xyz", "thunkit.org", "thxmate.com", "tittbit.in",
  "tmail.ws", "tmailinator.com", "toiea.com", "topica.email",
  "topranklist.de", "tormail.org", "trash2009.com", "trash-amil.com",
  "trash-mail.com", "trash-mail.de", "trash-mail.net", "trash2009.com",
  "trashdevil.com", "trashemail.de", "trashmail.at", "trashmail.com",
  "trashmail.de", "trashmail.me", "trashmail.net", "trashmail.org",
  "trashmail.ws", "trashmailer.com", "trashymail.com", "trbvm.com",
  "trialmail.de", "trillianpro.com", "turual.com", "twinmail.de",
  "tyldd.com", "ubismail.net", "uggsrock.com", "umail.net", "undo.it",
  "unforgettable-email.com", "unmail.ru", "upliftnow.com", "upxmail.com",
  "urloid.com", "valemail.net", "venompen.com", "verifymail.win",
  "veryrealemail.com", "vidchart.com", "viewcastmedia.com", "viewcastmedia.net",
  "vinernet.com", "vipmail.name", "vipmail.pw", "vipmail.eu",
  "vipmail.info", "vmail.me", "vmani.com", "vomoto.com", "vorga.org",
  "vsimcard.com", "vssms.com", "vtxmail.us", "vubby.com", "walala.org",
  "walkmail.net", "walkmail.ru", "wasteland.it", "watchmail.net",
  "webtrip.ch", "wee.my", "wegwerfmail.de", "wegwerfmail.net",
  "wegwerfmail.org", "wetrainbayarea.com", "wh4f.org", "whatiaas.com",
  "whatifanalytics.com", "whisperfocus.com", "whyspam.me", "wilemail.com",
  "willhackforfood.biz", "winemaven.info", "wisconsintechhelp.com",
  "wiz2.site", "wma.xyz", "wollmail.com", "wowmail.com",
  "writeme.com", "wronghead.com", "wuzup.net", "wuzupmail.net",
  "wwwnew.eu", "xagloo.com", "xemaps.com", "xents.com", "xing886.uu.gl",
  "xmail.com", "xmaily.com", "xoxy.net", "xwaretech.com", "xwaretech.info",
  "xwaretech.net", "xww.ro", "yep.it", "yopmail.com", "yopmail.fr",
  "yopmail.net", "yopmail.org", "yopmail29.co.vu", "yopmail81.co.vu",
  "ypmail.webarnak.fr.eu.org", "yugasandrika.com", "z1p.biz",
  "z5cp74.com", "zehnminutenmail.de", "zep-hyr.com", "zhcne.com",
  "zippymail.info", "zoaxe.com", "zoemail.com", "zoemail.net",
  "zoemail.org", "zomg.info", "zumpat.com", "zxcvbnm.com",
]);

const FREE_PROVIDERS = new Set([
  "gmail.com", "googlemail.com", "yahoo.com", "yahoo.co.nz", "yahoo.co.uk",
  "outlook.com", "hotmail.com", "live.com", "hotmail.co.nz", "outlook.co.nz",
  "icloud.com", "me.com", "mac.com", "protonmail.com", "proton.me",
  "pm.me", "zoho.com", "aol.com", "ymail.com", "mail.com",
  "inbox.com", "fastmail.com", "fastmail.fm", "tutanota.com",
  "tutamail.com", "tutanota.de", "gmx.com", "gmx.co.nz",
  "xtra.co.nz", "orcon.net.nz", "slingshot.co.nz", "vodafone.co.nz",
  "spark.co.nz", "2degrees.com", "freedomx.co.nz", "now.co.nz",
  "inspire.net.nz", "clear.net.nz", "ihug.co.nz", "paradise.net.nz",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@").pop()?.toLowerCase().trim();
  if (!domain) return false;
  if (DISPOSABLE_DOMAINS.has(domain)) return true;
  return false;
}

export function isKnownEmailProvider(domain: string): boolean {
  return FREE_PROVIDERS.has(domain.toLowerCase());
}
