import { doc, getDoc } from "firebase/firestore";
import { db } from "./firebase";

/** Suggest a handle from the email local part (before @). */
export function defaultUsernameFromEmail(email: string): string {
  const prefix = (email.split("@")[0] || "user").replace(/[^a-zA-Z0-9_]/g, "").slice(0, 20);
  return prefix || "user";
}

export function normalizeUsernameInput(raw: string): string {
  return raw.trim().replace(/^@+/, "").replace(/[^a-zA-Z0-9_]/g, "").slice(0, 30);
}

export function validateUsername(raw: string): { valid: boolean; error?: string } {
  const u = normalizeUsernameInput(raw);
  if (u.length < 3) {
    return { valid: false, error: "Username must be at least 3 characters." };
  }
  if (u.length > 30) {
    return { valid: false, error: "Username must be 30 characters or less." };
  }
  if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(u)) {
    return {
      valid: false,
      error: "Start with a letter; use letters, numbers, and underscores only.",
    };
  }
  return { valid: true };
}

export async function isUsernameAvailable(username: string, excludeUid?: string): Promise<boolean> {
  const key = normalizeUsernameInput(username).toLowerCase();
  if (!key) return false;
  const snap = await getDoc(doc(db, "usernames", key));
  if (!snap.exists()) return true;
  if (excludeUid && snap.data()?.uid === excludeUid) return true;
  return false;
}

/** True when username looks like an auto collision suffix (e.g. terangi + 4 random chars). */
export function looksAutoGeneratedUsername(username: string, email: string): boolean {
  const base = defaultUsernameFromEmail(email).toLowerCase();
  const u = username.toLowerCase();
  if (u === base) return false;
  return new RegExp(`^${base}[a-z0-9]{4}$`).test(u);
}
