import { describe, expect, it } from "vitest";
import {
  defaultUsernameFromEmail,
  looksAutoGeneratedUsername,
  validateUsername,
} from "./username";

describe("defaultUsernameFromEmail", () => {
  it.each([
    ["seller@example.com", "seller"],
    ["1st-seller@example.com", "user1stseller"],
    ["a@example.com", "auser"],
    ["!!!@example.com", "user"],
  ])("always creates a valid public handle for %s", (email, expected) => {
    const username = defaultUsernameFromEmail(email);
    expect(username).toBe(expected);
    expect(validateUsername(username).valid).toBe(true);
  });

  it("recognizes generated collision candidates at the maximum base length", () => {
    const email = "abcdefghijklmnopqrst@example.com";
    expect(defaultUsernameFromEmail(email)).toBe("abcdefghijklmnopqrst");
    expect(looksAutoGeneratedUsername("abcdefghijklmnopqrst2", email)).toBe(true);
    expect(looksAutoGeneratedUsername("abcdefghijklmnopqrst", email)).toBe(false);
  });
});
