import { doc, getDoc } from "firebase/firestore";
import { db } from "./firebase";

/** Suggest a handle from the email local part (before @). */
export function defaultUsernameFromEmail(email: string): string {
  const local = (email.split("@")[0] || "").replace(/[^a-zA-Z0-9_]/g, "");
  const withLetterPrefix = /^[a-zA-Z]/.test(local) ? local : `user${local}`;
  const candidate = (withLetterPrefix || "user").slice(0, 20);
  return candidate.length >= 3 ? candidate : `${candidate}user`.slice(0, 20);
}

export function normalizeUsernameInput(raw: string): string {
  return raw.trim().replace(/^@+/, "").replace(/[^a-zA-Z0-9_]/g, "").slice(0, 30);
}

export function validateUsername(raw: string): { valid: boolean; error?: string } {
  const u = normalizeUsernameInput(raw);
  if (u.length < 3) {
    return { valid: false, error: "Username must be at least 3 characters." };
  }
  if (u.length > 30) {
    return { valid: false, error: "Username must be 30 characters or less." };
  }
  if (!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(u)) {
    return {
      valid: false,
      error: "Start with a letter; use letters, numbers, and underscores only.",
    };
  }
  return { valid: true };
}

export async function isUsernameAvailable(username: string, excludeUid?: string): Promise<boolean> {
  const key = normalizeUsernameInput(username).toLowerCase();
  if (!key) return false;
  const snap = await getDoc(doc(db, "usernames", key));
  if (!snap.exists()) return true;
  if (excludeUid && snap.data()?.uid === excludeUid) return true;
  return false;
}

/** True when username is one of the generated collision candidates (e.g. terangi2). */
export function looksAutoGeneratedUsername(username: string, email: string): boolean {
  const base = defaultUsernameFromEmail(email).toLowerCase();
  const u = username.toLowerCase();
  if (u === base) return false;
  for (let attempt = 1; attempt < 20; attempt++) {
    const suffix = String(attempt + 1);
    const candidate = `${base.slice(0, 30 - suffix.length)}${suffix}`;
    if (u === candidate) return true;
  }
  return false;
}
